doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from Mosparo\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations/%env(database_system)%'
    enable_profiler: false
