name: Docker Multi-Platform Build and Push

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v2

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          context: docker/
          platforms: linux/i386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v5
          push: true
          tags: mosparo/mosparo:${{ github.ref_name }}
          build-args: |
            MOSPARO_VERSION=${{ github.ref_name }}

      - name: Build only on manual trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v2
        with:
          context: docker/
          platforms: linux/i386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v5
          tags: mosparo/mosparo:${{ steps.ghd.outputs.tag }}
          build-args: |
            MOSPARO_VERSION=${{ steps.ghd.outputs.tag }}
